[package]
name = "stockism"
version = "0.1.0"
authors = ["Werner <werner_a_e@yahoo.es>"]

[dependencies]
router = "*"
diesel = { version = "0.14.0", features = ["postgres"] }
diesel_codegen = { version = "0.14.0", features = ["postgres"] }
dotenv = "0.9.0"

[dependencies.iron]
version = "*"
